name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        id: install_rust
        run: |
          ARCH=$(uname -m)
          APPIMAGE_NAME="iriswallet-${ARCH}.AppImage"
          echo "APPIMAGE_NAME=${APPIMAGE_NAME}" >> $GITHUB_ENV
          echo $APPIMAGE_NAME

      - name: Check AppImage name
        run: |
          echo $APPIMAGE_NAME
