name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          ARCH=$(uname -m)
          APPIMAGE_NAME="iriswallet-${ARCH}.AppImage"
          echo $APPIMAGE_NAME
      - name: check app name
        run: |
          echo $APPIMAGE_NAME

          
