name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          echo "ARCH=$(uname -m)" >> $GITHUB_ENV
          APPIMAGE_NAME="iriswallet-${{ env.ARCH }}.AppImage"
          echo $APPIMAGE_NAME
